// eslint-disable-next-line no-unused-vars
declare namespace NodeJS {
  export interface ProcessEnv {
    ALCHEMY_DEV_URL_RINKEBY: string
    ALCHEMY_URL_MAINNET: string
    NEXT_PUBLIC_APPPAGE_URL: string
    NEXT_PUBLIC_DEFAULT_NFT_PRICE: string
    NEXT_PUBLIC_DEFAULT_PILL_PRICE: string
    NEXT_PUBLIC_DEPLOYED_NETWORK: string
    NEXT_PUBLIC_NFT_CONTRACT_ADDRESS: string
    NEXT_PUBLIC_DISTRIBUTOR_CONTRACT_ADDRESS: string
    NEXT_PUBLIC_ECM_CONTRACT_ADDRESS: string
    NEXT_PUBLIC_HOMEPAGE_URL: string
    NEXT_PUBLIC_IPFS_NODE: string
    NEXT_PUBLIC_OPENSEA_COLLECTION_URL: string
    NEXT_PUBLIC_PHARMACY_CONTRACT_ADDRESS: string
    NEXT_PUBLIC_PILL_CONTRACT_ADDRESS: string
    NEXT_PUBLIC_PORTIS_DAPP_ID: string
    NEXT_PUBLIC_PRESALE_CONTRACT_ADDRESS: string
    NEXT_PUBLIC_PRESALE_DATE: string
    NEXT_PUBLIC_PRESALE_NFT_PRICE: string
    NEXT_PUBLIC_RELEASE_DATE: string
    NEXT_PUBLIC_RPC_URL_1: string
    NEXT_PUBLIC_RPC_URL_4: string
    NEXT_PUBLIC_WHITELIST_DATE: string
  }
}
